spring.application.name=dronetrack

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dronetrack
spring.datasource.username=dronetrack
spring.datasource.password=dronetrack123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# OpenSky
opensky.api.url=https://opensky-network.org/api
geofence.check.interval=10000
